### ISSUE TITLE
Implement replacement for libucl

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rust-nereon#10]
We need something native in Rust that parses nereon syntax (https://github.com/riboseinc/nereon-syntax) to replace the libucl dependency.

**Comment by drystone** [comment]
Sorry @jjr840430, for the delay. Sure, just as soon as I'm up and running I'll post my ID to RD.

**Comment by jjr840430** [comment]
@ronaldtse @drystone 
How about separating repo for parsing UCL structure?
i.e. like as [libucl](https://github.com/vstakhov/libucl) or [hcl](https://github.com/hashicorp/hcl).

**Comment by drystone** [comment]
[Bindings](https://crates.io/crates/ucl) already exist for Rust so we've decided not to replicate the effort :)
