### ISSUE TITLE
Which license applies to rust-nereon?

### ISSUE THREAD

**Issue by abronan** [riboseinc/rust-nereon#11]
Hi,

I was looking for a rust binding to libucl and stumbled upon nereon, very cool project :)

Although I'm wondering about the license that is applied here? (no LICENSE file) Do you have any more info on this?

Thanks!

**Comment by drystone** [comment]
It's BSD 2 clause. The license is at the top of the source files. I'll ad a LICENCE file shortly.

A word of warning though: the UCL functionality is soon to be replaced with our own parser for a UCL-like language, NOC,  which allows inline expressions, templates and other interpolations. This means we won't be maintaining the UCL code (unless we split it off into it's own crate). Feel free to use though and maybe check out the new syntax (in the parser branch) - perhaps that will be of use to you too.

**Comment by ronaldtse** [comment]
@drystone in this case can we split off rust-ucl / rust-libucl to a separate crate?

Since we already have it people who need it could use it too. :wink:

**Comment by drystone** [comment]
Hmmm, was about to publish to crates.io but found [an existing libucl wrapper](https://crates.io/crates/ucl) which is considerably more extensive than ours!
